# Generated by Django 4.1 on 2022-10-12 06:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(choices=[('cod', 'Cash On Delivery'), ('gpay', 'Google Pay on 98989898998')], max_length=4, null=True)),
                ('grandtotal', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_update_date', models.DateField(auto_now=True)),
                ('order_status', models.CharField(choices=[('received', 'Order Received'), ('process', 'Order In Process'), ('Shipped', 'Order Shipped'), ('delivered', 'Order Delivered'), ('pending', 'Order Pending'), ('delayed', 'Order Delayed'), ('Cancelled', 'Order Cancelled')], default='received', max_length=10, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('details', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('featured_product', models.BooleanField()),
                ('datetime_of_entry', models.DateTimeField()),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='productpics')),
                ('product_pic2', models.ImageField(blank=True, null=True, upload_to='productpics')),
                ('product_pic3', models.ImageField(blank=True, null=True, upload_to='productpics')),
                ('qty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productshopping.category')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=500, null=True)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productshopping.product')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productshopping.category')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=50, null=True)),
                ('qty', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('sessionid', models.CharField(max_length=500, null=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productshopping.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productshopping.subcategory'),
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('orderno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productshopping.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productshopping.product')),
            ],
        ),
    ]
